/**
 * Purpose: Thin wrapper over the S3-compatible object storage client used
 * by the document vault (MinIO locally, a real bucket in production).
 * Responsibilities: Upload a buffer under a random object key, and mint
 * short-lived signed GET URLs.
 * Security: Object keys are random UUIDs generated by the caller, never
 * derived from a filename or plate number (docs/PRIVACY_DATA_MAP.md).
 * Signed URLs default to a 5-minute expiry and are never logged.
 * Related: documents.service.ts, docs/DEPLOYMENT.md (S3_* env vars).
 */
import { Inject, Injectable } from '@nestjs/common';
import { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { APP_CONFIG, type AppConfig } from '../../config/config.module';

const SIGNED_URL_TTL_SECONDS = 5 * 60;

@Injectable()
export class StorageService {
  private readonly client: S3Client;

  constructor(@Inject(APP_CONFIG) private readonly config: AppConfig) {
    this.client = new S3Client({
      endpoint: this.config.S3_ENDPOINT,
      region: 'us-east-1',
      forcePathStyle: true,
      credentials: {
        accessKeyId: this.config.S3_ACCESS_KEY_ID ?? '',
        secretAccessKey: this.config.S3_SECRET_ACCESS_KEY ?? '',
      },
    });
  }

  async upload(objectKey: string, body: Buffer, contentType: string): Promise<void> {
    await this.client.send(
      new PutObjectCommand({ Bucket: this.config.S3_BUCKET, Key: objectKey, Body: body, ContentType: contentType }),
    );
  }

  async getSignedDownloadUrl(objectKey: string): Promise<{ url: string; expiresAt: string }> {
    const command = new GetObjectCommand({ Bucket: this.config.S3_BUCKET, Key: objectKey });
    const url = await getSignedUrl(this.client, command, { expiresIn: SIGNED_URL_TTL_SECONDS });
    return { url, expiresAt: new Date(Date.now() + SIGNED_URL_TTL_SECONDS * 1000).toISOString() };
  }

  async delete(objectKey: string): Promise<void> {
    await this.client.send(new DeleteObjectCommand({ Bucket: this.config.S3_BUCKET, Key: objectKey }));
  }
}
